# Alembic configuration file for Auth Service

[alembic]
# path to migration scripts
sqlalchemy.url = postgresql://postgres:postgres@localhost:5432/formacion_auth

# Template used to generate migration file names
file_template = %%(rev)s_%%(slug)s

# sys.path path, will be prepended to sys.path if present
prepend_sys_path = .

# timezone to use when rendering the date
# string value is passed to os.environ['TZ'] on Unix-like systems
# (e.g. 'US/Eastern', 'Europe/Paris')
# timezone =

# max length of characters to apply to the
# "slug" field that's appended to a revision file
# (affects the length of the file name as well as the content of its
# migration.Rev.branch_label value)
# truncate_slug_length = 40

# set to 'true' to run the environment during
# the 'revision' command, regardless of autogenerate
# revision_environment = false

# set to 'true' to allow .pyc and .pyo files without
# a source .py file to be detected as revisions in the
# versions/ directory
# sourceless = false

# logging configuration
# Loggers to configure
[loggers]
keys = root,sqlalchemy,alembic

[handlers]
keys = console

[formatters]
keys = generic

[logger_root]
level = WARN
handlers = console
qualname =

[logger_sqlalchemy]
level = WARN
handlers =
qualname = sqlalchemy.engine

[logger_alembic]
level = INFO
handlers =
qualname = alembic

[handler_console]
class = StreamHandler
args = (sys.stderr,)
level = NOTSET
formatter = generic

[formatter_generic]
format = %(levelname)-5.5s [%(name)s] %(message)s
datefmt = %H:%M:%S
